version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=042794132985.dkr.ecr.us-east-1.amazonaws.com/dfly-app
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t Dfly-$REPOSITORY_URI:$IMAGE_TAG -f ./DFly-Docker/Dockerfile .
      - docker build -t Nginx-$REPOSITORY_URI:$IMAGE_TAG -f ./NGINX/Dockerfile .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push Dfly-$REPOSITORY_URI:$IMAGE_TAG
      - docker push NGINX-$REPOSITORY_URI:$IMAGE_TAG
